### PR TITLE
Removed comma from CSS selector causing an error

### PR DESCRIPTION
**Pull request by rctgamer3**

### CODE REVIEW

**Comment by rctgamer3** [comment]
Canceling PR since you seem to be working on v2.0 on a different branch and the error doesn't seem to be present there anymore.

**Comment by Noitidart** [comment]
Thanks so much for this man!Is this bug due to browser update?

Are you on Windows? You can try the new version its real kick ass, but I need some time to focus on it. It's very intricate (not fragile), just very interconnected. So I need to spend days thinking and carefully doing. Im hoping I get some time I reallllly want to bring that out.

**Comment by rctgamer3** [comment]
There's no visual bug, but it errors to the browser/error console. I already reported this in the last review (check your email) but I thought I'd help you out a bit.

**Comment by Noitidart** [comment]
Thanks @rctgamer3 it does help a lot. I badly want to get v2 out i just need a solid block of time to dedicate it. Do you use windows? I have some beta users who are using it despite some annoying issues. You can beta it: https://www.youtube.com/watch?v=fKw-BNWMyQM

**Pull request closed without merging**
